---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: upgrade packages
    apt:
      name: "*"
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution == "Sangoma"

  - name: upgrade packages
    yum:
      name: "*"
      state: latest
    when: ansible_distribution == "Sangoma"
